config/routes.rb
Rails.application.routes.draw do
  resources :kontoumsaetzes do 
    collection { post :import }
  end

  resources :posts
  devise_for :users, controllers: { registrations: 'registrations'}
  
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  root to: 'static#home'

  get 'static/contact'

  post 'static/thank_you'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kontoumsaetze.rb
class Kontoumsaetze < ApplicationRecord
  belongs_to :user

  validates_presence_of :weg, :wertstellung, :umsatzart, :buchungsdetails, :auftraggeber, :empfaenger, :betrag, :saldo

  scope :kontoumsaetze_by, ->(user) { where(user_id: user.id) }
 
  def self.import(file)
    CSV.foreach(file.path, headers: true, col_sep: ';') do |row|
      Kontoumsaetze.create! row.to_hash
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content, :date
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :kontoumsaetzes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :first_name, :last_name

  def full_name
    last_name.capitalize + ", " + first_name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  def admin_types
    ['AdminUser']
  end

  def after_sign_in_path_for(resource)
    posts_path
  end
  
end

app/controllers/kontoumsaetzes_controller.rb
class KontoumsaetzesController < ApplicationController
  before_action :set_kontoumsaetze, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    if admin_types.include?(current_user.type)
      @kontoumsaetzes = Kontoumsaetze.order(sort_column + " " + sort_direction).page(params[:page]).per(10)
    else
      @kontoumsaetzes = Kontoumsaetze.kontoumsaetze_by(current_user).page(params[:page]).per(8)
    end

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def new
    if admin_types.include?(current_user.type)
      @kontoumsaetze = Kontoumsaetze.new
    else
      redirect_to kontoumsaetzes_path, alert: 'Access denied'
    end
  end

  def create
    @kontoumsaetze = Kontoumsaetze.new(kontoumsaetze_params)
    #@kontoumsaetze.user_id = current_user.id
    #@user = @finance.user(params[:id])

    if @kontoumsaetze.save
      redirect_to @kontoumsaetze, notice: "Kontoumsätze gespeichert"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @kontoumsaetze.update(kontoumsaetze_params)
      redirect_to @kontoumsaetze, notice: 'Ihre Kontoumsätze wurde erfolgreich aktualisiert'
    else
      render :edit
    end
  end

  def destroy
    @kontoumsaetze.delete
    redirect_to kontoumsaetzes_path, notice: 'Ihre Kontoumsätze wurde erfolgreich entfernt'
  end

  def import
    Kontoumsaetze.import(params[:file])
    redirect_to kontoumsaetzes_path, notice: "Erfolgreich importiert"
  end

  private

    def kontoumsaetze_params
      params.require(:kontoumsaetze).permit(:weg, :wertstellung, :umsatzart, :buchungsdetails, :auftraggeber, :empfaenger, :betrag, :saldo, :user_id)
    end

    def set_kontoumsaetze
      @kontoumsaetze = Kontoumsaetze.find(params[:id])
    end

    def sort_column
      params[:sort] || "weg"
    end

    def sort_direction
      params[:direction] || "asc"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index  
    @posts = Post.page(params[:page]).per(3)
   # @posts = Post.order('created_at DESC').limit(3)
  end

  def new
    if admin_types.include?(current_user.type)
      @post = Post.new
    else
      redirect_to posts_path, alert: 'Access denied'
    end
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Nachricht gespeichert"
    else
      render :new
    end
  end

  def show
  end

  def edit 
    authorize @post 
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to @post, notice: 'Ihre Nachricht wurde erfolgreich aktualisiert'
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Ihre Nachricht wurde erfolgreich entfernt'
  end


  private

  def post_params
    params.require(:post).permit(:title, :content, :date)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(from: @email,
        to: 'jochum.de.bueger@gmail.com',
        subject: "A new contact form message from #{@name}",
        body: @message).deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction 
  end

  def admin_types
    ['AdminUser']
  end


  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/kontoumsaetzes_helper.rb
module KontoumsaetzesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/kontoumsaetzes/_form.html.erb
<%= form_for @kontoumsaetze, class: "form-horizontal" do |f| %>
  
<!--   <#% if kontoumsaetze.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(kontoumsaetze.errors.count, "error") %> prohibited this kontoumsaetze from being saved:</h2>

      <ul>
      <#% kontoumsaetze.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <#% end %>
      </ul>
    </div>
  <#% end %> -->

  <% if @kontoumsaetze.errors.any? %>
    <% @kontoumsaetze.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Sudetenlandweg 1010a", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= collection_select( :kontoumsaetze, :user_id, User.all, :id, :last_name, {}, { :multiple => false } ) %>
  </div>

  <div class="form-group">
    <%= f.label :weg, class: "col-sm-2 control-label" %>
    <%= f.number_field :weg, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :wertstellung, class: "col-sm-2 control-label" %>
    <%= f.text_field :wertstellung, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :umsatzart, class: "col-sm-2 control-label" %>
    <%= f.text_field :umsatzart, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :buchungsdetails, class: "col-sm-2 control-label" %>
    <%= f.text_field :buchungsdetails, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :auftraggeber, class: "col-sm-2 control-label" %>
    <%= f.text_field :auftraggeber, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :empfaenger, class: "col-sm-2 control-label" %>
    <%= f.text_field :empfaenger, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :betrag, class: "col-sm-2 control-label" %>
    <%= f.text_field :betrag, :step => 0.01, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :saldo, class: "col-sm-2 control-label" %>
    <%= f.text_field :saldo, :step => 0.01, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Speichern', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/kontoumsaetzes/_kontoumsaetze.html.erb
<tr>
  <td><%= kontoumsaetze.user.full_name %></td>
  <td><%= kontoumsaetze.weg %></td>
  <td><%= kontoumsaetze.wertstellung %></td>
  <td><%= kontoumsaetze.umsatzart %></td>
  <td><%= kontoumsaetze.buchungsdetails.truncate(15) %></td>
  <td><%= kontoumsaetze.auftraggeber.truncate(15) %></td>
  <td><%= kontoumsaetze.empfaenger.truncate(15) %></td>
  <td><%= number_to_currency(kontoumsaetze.betrag, :unit=>'€') %></td>
  <td><%= number_to_currency(kontoumsaetze.saldo, :unit=>'€') %></td>

  <% if current_user.try(:type) == 'AdminUser' %>
    <td><%= link_to 'Zeigen', kontoumsaetze %></td>
    <td><%= link_to 'Bearbeiten', edit_kontoumsaetze_path(kontoumsaetze), id: "edit_#{kontoumsaetze.id}" %></td>
    <td><%= link_to 'Löschen', kontoumsaetze_path(kontoumsaetze), id: "delete_kontoumsaetze_#{kontoumsaetze.id}_from_index", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/kontoumsaetzes/edit.html.erb
<h2>Kontoumsätze bearbeiten</h2>

<%= render 'form' %>

app/views/kontoumsaetzes/index.html.erb
<div style="padding-top: 50px;">

  <table class="table table-striped table-hover table-details">
    <thead>
      <tr>
        <th>Bewohner</th>
        <th><%= sortable "weg", "WEG" %></th>
        <th><%= sortable "wertstellung", "Wertstellung" %></th>
        <th><%= sortable "umsatzart", "Umsatzart" %></th>
        <th><%= sortable "buchungsdetails", "Buchunsdetails" %></th>
        <th><%= sortable "auftraggeber", "Auftraggeber" %></th>
        <th><%= sortable "empfaenger", "Empfänger" %></th>
        <th><%= sortable "betrag", "Betrag" %></th>
        <th><%= sortable "saldo", "Saldo" %></th>
      </tr>
    </thead>

    <tbody >
      <%= render @kontoumsaetzes %>
    </tbody>
  
  </table>

  <div>
    <%= paginate @kontoumsaetzes %>
  </div>


  <% if current_user.try(:type) == 'AdminUser' %>
    <%= link_to "Export", kontoumsaetzes_path(format: "xlsx"), style: "float: right;" %>

    <%= form_tag import_kontoumsaetzes_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import Datei", class: 'btn btn-primary', style: "margin-top: 5px;" %>
    <% end %>

  <% end %>
</div>

app/views/kontoumsaetzes/index.js.erb
$('#kontoumsaetzes').html('<%= escape_javascript render(@kontoumsaetzes) %>');
$('#paginator').html('<%= escape_javascript(paginate(@kontoumsaetzes, remote: true).to_s) %>');

app/views/kontoumsaetzes/new.html.erb
<h2>Neue Kontoumsätze</h2>

<%= render 'form' %>

app/views/kontoumsaetzes/show.html.erb
<%= @kontoumsaetze.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WegBetreuung</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container" style="margin-left: 45px; margin-right: 45px;">
    <div class="row">
      <div class="col-md-12">
       <%= render 'shared/alerts' %>
       <%= render 'shared/nav' %>
        <%= yield %> 
      </div>
    </div>

  </body>

</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Sudetenlandweg 1010a", sticky: false) %>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "col-sm-2 control-label" %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <%= f.date_field :date, class: "form-control" %>
  </div>

  <%= f.submit 'Speicher', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4">
  <div style="padding: 25px;">
    <%= link_to(post) do %>
      <h3 style="color: #337ab7;">
        <%= post.title %>
      </h3>
    <% end %>
    <hr>
    <p style="font-size: 0.8em; color: #777777; "><i><%= post.date %></i></p>
    <p>
      <%= post.content.truncate(250) %>
    </p>
    <% if current_user.try(:type) == 'AdminUser' %>
      <%= link_to 'Bearbeiten', edit_post_path(post), id: "edit_#{post.id}" %>
      <%= link_to 'Löschen', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", data: { confirm: 'Sind Sie sicher?' } %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Nachricht bearbeiten</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div id="posts">
  <%= render @posts %>
</div>

<div id="paginator" class="col-md-12">
  <%= paginate @posts, remote: true %>
</div>

<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.email %><br/>
  <%= user.full_name %><br/>
<% end %>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h1>Neuer Nachricht</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div style="width: 80%; margin: auto; text-align: center;">
    <div style="padding: 25px;">
      <h3 style="color: #337ab7;">
      <%= @post.title %>
      </h3>
      <hr>
      <p style="font-size: 0.8em; color: #777777; "><i><%= @post.date %></i></p>
      <p>
        <%= simple_format(@post.content) %>
      </p>
      <%= link_to 'Bearbeiten', edit_post_path(@post), id: "edit_#{@post.id}" %>
      <%= link_to 'Löschen', post_path(@post), method: :delete, id: "delete_post_#{@post.id}_from_index", data: { confirm: 'Sind Sie sicher?' } %>
    </div>
  </div>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Sudetenlandweg 1010a", sticky: false, time: 3000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Sudetenlandweg 1010a", sticky: false, time: 3000) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Sudetenlandweg 1010a", sticky: false, time: 3000) %>
<% end %>

app/views/shared/_nav.html.erb
<div class='logo' style="height: 100px;">
  <h1>WEG BETREUUNG</h1>
</div>

<% if current_user %>
  <ul class="nav nav-tabs">
    <li class="<%= active?(posts_path) %>">
      <%= link_to "Home", posts_path %>
    </li>
    <li class="<%= active?(kontoumsaetzes_path) %>">
      <%= link_to "Kontoumsätze", kontoumsaetzes_path %>
    </li>
    <li class="<%= active?(root_path) %>">
      <%= link_to "Kontakt", static_contact_path %>
    </li>
  <!--   <li class="disabled">
      <a href="#">Messages</a>
    </li> -->
    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Dropdown<strong class="caret"></strong></a>
      <ul class="dropdown-menu">
        <% if current_user.try(:type) == 'AdminUser' %>
          <li>
            <%#= link_to "Bewohner bearbeiten", edit_user_registration_path, %>
          </li>
          <li>
            <%= link_to "Nachricht schreiben und bearbeiten", new_post_path %>
          </li>
          <li>
            <%= link_to "Neue Kontoumsätze hochladen", new_kontoumsaetze_path %>
          </li>
          <li>
            <%= link_to "Kontoumsätze hochladen met excel und bearbeiten", kontoumsaetzes_path %>
          </li>
          </li>
            <li class="divider">
          </li>
        <% end %>
        <li>
          <%= link_to "Abmelden", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>